# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: todo-user 
      POSTGRES_PASSWORD: todo-password 
      POSTGRES_DB: todo-db 
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    # volumes:
        # - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        # - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080